### ISSUE TITLE
I wonder if this is a bug?

### ISSUE THREAD

**Issue by DbuyCN** [InvisibleManVPN/InvisibleMan-XRayClient#151]
I encountered a strange problem. I can't get online by opening the chrome browser first and launching the invisibleman next, only when I open the invisibleman first and then launch the browser after that I can get online properly.

Windows7 X64

**Comment by InvisibleManVPN** [comment]
Hey @DbuyCN,
That's strange to me. It shouldn't related to the app. Do you have any new updates?

**Comment by nelfco** [comment]
I have a similar problem. When I turn on my PC, there is no internet connection. I go into Invisible Man XRay, start the proxy, then disconnect. Internet connection appears. Windows 11, before installing Invisible Man XRay I did not have such problems. This is similar on two of my PCs.

**Comment by DbuyCN** [comment]
The system proxy cannot be turned on automatically, it must be done manually.
Open the computer proxy settings and click Confirm to take effect.

**Comment by nelfco** [comment]
Of course it can't. And yet it does. That's why it's assumed to be some kind of bug. Proxy settings are clean in Windows. And, again, the problem occurs on two different computers. Also, turning proxy on and off breaks some Windows applications. Telegram, for example. Completely turning off the application helps. Before switching to VLESS, I used OpenVPN and compatible programs, and this problem was not observed.

**Comment by pochtineploho** [comment]
I have the same problem on my devices.

**Comment by InvisibleManVPN** [comment]
@DbuyCN, @nelfco, @pochtineploho Refer to #162, this problem will be fixed in the next release.
