### ISSUE TITLE
这个app的config不支持dns和rout ing

### ISSUE THREAD

**Issue by Bearljj** [InvisibleManVPN/InvisibleMan-XRayClient#41]

**Comment by Bearljj** [comment]
我直接复制了https://raw.githubusercontent.com/XTLS/Xray-examples/main/VLESS-TCP-XTLS-Vision/config_client.json这个链接，提示错误，如果把dns和routing都删掉就可以工作

**Comment by InvisibleManVPN** [comment]
Hello @Bearljj!
Thank you for posting this topic. That's true. We should fix this problem. We will investigate the issue and send you the feedback.

**Comment by InvisibleManVPN** [comment]
@Bearljj This problem occurs because there are no `geoip.dat` and `geosite.dat` files in the Invisible Man XRay root folder. We'll fix this problem in our new release. But if you want to use it in your current version, you should install these two files manually and replace them in the root folder.

Follow these steps:
- Download `geoip.dat` from this link (https://github.com/v2fly/geoip/releases/latest/download/geoip.dat)
- Download `dlc.dat` from this link (https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat)
- Rename `dlc.dat` to `geosite.dat`
- Copy both dat files, go to the Invisible Man XRay root folder and paste them beside the `Invisible Man Xray.exe` file.
- Run the app.

**Comment by InvisibleManVPN** [comment]
Don't close this topic because we should fix this problem and after that, we will close it.
